[project]
name = "fable-pprl-service"
version = "0.2.0"
description = "HTTP-based service for performing privacy-preserving record linkage with Bloom filters in the FABLE ecosystem."
authors = [
    {name = "Maximilian Jugl"},
    {name = "Paul Brassel", email = "paul.brassel@medizin.uni-leipzig.de"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard] (>=0.115.11,<1)",
    "fable-core (>=0.2.0,<0.3.0)",
    "fable-model (>=0.2.0,<0.3.0)",
    "bitarray (>=3.8.1,<4.0.0)",
    "starlette (>=1.2.1,<2.0.0)",
    "pyphonetics (>=0.5.3,<0.6.0)",
]
license = "MIT"
keywords = ["record linkage", "privacy", "bloom filter", "bitarray", "cryptography", "service", "api"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Scientific/Engineering",
    "Topic :: Security :: Cryptography",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"
]

[project.scripts]
fable-pprl-service = "pprl_service.main:run_server"

[project.urls]
repository = "https://github.com/ul-mds/fable-pprl-service"

[tool.poetry]
packages = [{ include = "pprl_service" }]

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
markers = [
    "integration: mark a test as an integration test."
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
ruff = ">=0.15.0"
pytest = ">=8.3.0"
faker = "^40.0.0"
pytest-cov = "^7.1.0"
pre-commit = "^4.6.0"
readme-coverage-badger = "^1.1.0"
httpx2 = "^2.3.0"
